/** @format */

import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/ui/app-header";
import { AppPreferencesProvider } from "@/lib/app-preferences";
import { CardCursorGlowBinder } from "@/components/ui/card-cursor-glow";

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${geistMono.variable} antialiased`}>
        <AppPreferencesProvider>
          <CardCursorGlowBinder />
          <AppHeader />
          {children}
        </AppPreferencesProvider>
      </body>
    </html>
  );
}
